#!/bin/bash
# =============================================================================
# RV AI Skills Hub — Bootstrap & Update Script
#
# Usage:
#   bash setup.sh              Full setup (directories, Codex sync, vendor clone)
#   bash setup.sh --update     Pull latest vendor repos and regenerate lockfile
#   bash setup.sh --link       Regenerate external/ symlinks from registry
#
# Compatible with Bash 3.2+ (macOS default).
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

SUCCEEDED=""
FAILED=""
LOCKFILE=".vendor.lock"

# ── Vendor configuration ────────────────────────────────────────────────────
# Parallel arrays (Bash 3.2 compatible — no associative arrays).
VENDOR_NAMES=(anthropic huggingface openai vercel)
VENDOR_URLS=(
    "https://github.com/anthropics/skills.git"
    "https://github.com/huggingface/skills.git"
    "https://github.com/openai/skills.git"
    "https://github.com/vercel-labs/agent-skills.git"
)

# ── Sync a single vendor ────────────────────────────────────────────────────
sync_vendor() {
    local name=$1
    local url=$2
    local dest=".vendor/$name"

    if [ -d "$dest/.git" ]; then
        echo "  Updating $name..."
        if (cd "$dest" && git pull --quiet 2>/dev/null); then
            echo "  + $name updated."
            SUCCEEDED="$SUCCEEDED $name"
        else
            echo "  ! $name — pull failed."
            FAILED="$FAILED $name"
        fi
    else
        echo "  Cloning $name..."
        if git clone --depth 1 --quiet "$url" "$dest" 2>/dev/null; then
            echo "  + $name cloned."
            SUCCEEDED="$SUCCEEDED $name"
        else
            echo "  ! $name — clone failed. URL may require authentication."
            FAILED="$FAILED $name"
        fi
    fi
}

# ── Generate .vendor.lock ───────────────────────────────────────────────────
generate_lockfile() {
    echo "# Generated by setup.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOCKFILE"
    echo "# Tracks vendor commit SHAs for reproducibility." >> "$LOCKFILE"
    echo "" >> "$LOCKFILE"

    for name in "${VENDOR_NAMES[@]}"; do
        local dest=".vendor/$name"
        if [ -d "$dest/.git" ]; then
            local sha
            sha=$(cd "$dest" && git rev-parse HEAD 2>/dev/null || echo "unknown")
            local date_str
            date_str=$(cd "$dest" && git log -1 --format=%ci 2>/dev/null || echo "unknown")
            echo "$name: $sha  # $date_str" >> "$LOCKFILE"
        fi
    done

    echo ""
    echo "  Lockfile written: $LOCKFILE"
}

# ── Regenerate external/ symlinks ───────────────────────────────────────────
regenerate_symlinks() {
    echo ""
    echo "-- Regenerating external/ symlinks ----------------------------------------"

    if ! command -v python3 &>/dev/null; then
        echo "  Skipping: python3 required for symlink generation."
        return
    fi

    if ! python3 -c "import yaml" 2>/dev/null; then
        echo "  Skipping: pyyaml required. Install with: pip install pyyaml"
        return
    fi

    python3 -c "
import os, yaml

with open('_registry.yaml') as f:
    reg = yaml.safe_load(f)

vendors = reg.get('vendors', {})
external = reg.get('skills', {}).get('external', {})

for vendor, skills in external.items():
    vendor_cfg = vendors.get(vendor, {})
    skills_path = vendor_cfg.get('skills_path', 'skills')
    ext_dir = os.path.join('external', vendor)
    os.makedirs(ext_dir, exist_ok=True)

    for skill_entry in skills:
        name = skill_entry['name'] if isinstance(skill_entry, dict) else skill_entry
        enabled = skill_entry.get('enabled', True) if isinstance(skill_entry, dict) else True

        link_path = os.path.join(ext_dir, name)
        target = os.path.join('..', '..', '.vendor', vendor, skills_path, name)

        if not enabled:
            if os.path.lexists(link_path):
                os.remove(link_path)
                print(f'  Removed disabled symlink: {link_path}')
            continue

        if os.path.lexists(link_path):
            continue

        try:
            os.symlink(target, link_path)
            print(f'  + {link_path} -> {target}')
        except OSError as e:
            print(f'  ! Failed to create symlink {link_path}: {e}')
"
    echo "  Done."
}

# ── Print summary ───────────────────────────────────────────────────────────
print_summary() {
    echo ""
    echo "-- Summary ----------------------------------------------------------------"
    [ -n "$SUCCEEDED" ] && echo "  Vendors synced:$SUCCEEDED" || true
    [ -n "$FAILED" ]    && echo "  Vendors failed:$FAILED" || true
}

# ── Main ────────────────────────────────────────────────────────────────────

if [ "${1:-}" = "--update" ]; then
    echo ""
    echo "-- Updating vendor repositories -------------------------------------------"
    for i in "${!VENDOR_NAMES[@]}"; do
        sync_vendor "${VENDOR_NAMES[$i]}" "${VENDOR_URLS[$i]}"
    done
    generate_lockfile
    regenerate_symlinks
    print_summary
    echo ""
    exit 0
fi

if [ "${1:-}" = "--link" ]; then
    regenerate_symlinks
    exit 0
fi

# ── Full setup (default) ────────────────────────────────────────────────────
echo ""
echo "-- Creating directory structure ---------------------------------------------"
mkdir -p core
mkdir -p .vendor
mkdir -p external/anthropic
mkdir -p external/huggingface
mkdir -p external/vercel
mkdir -p external/openai
echo "  Done."

echo ""
echo "-- Validating core skills ---------------------------------------------------"
if command -v python3 &>/dev/null && python3 -c "import yaml" 2>/dev/null; then
    python3 adapters/skill_loader.py --validate || true
else
    echo "  Skipping: python3 with pyyaml required. Install with: pip install pyyaml"
fi

echo ""
echo "-- Syncing core skills to Codex global instructions -------------------------"
python3 adapters/skill_loader.py --sync-all

echo ""
echo "-- Syncing vendor repositories ----------------------------------------------"
for i in "${!VENDOR_NAMES[@]}"; do
    sync_vendor "${VENDOR_NAMES[$i]}" "${VENDOR_URLS[$i]}"
done

generate_lockfile
regenerate_symlinks
print_summary

echo ""
echo "  Core skills are ready for Codex on this machine."
echo "  Run 'bash setup.sh --update' anytime to pull latest vendor changes."
echo ""
